{% set version = "1.1.0" %}

package:
  name: dart-adna
  version: {{ version }}

source:
  url: https://github.com/genomewalker/dart/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 16cd240366e92c938e37d7f2359dfa66e2cf9ee8ea1d58e8cde34a05011fcf1a

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('dart-adna', max_pin='x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake >=3.18
    - make
    - pkg-config
  host:
    - zlib
    - zstd
    - libgomp        # [linux]
    - llvm-openmp    # [osx]
  run:
    - zlib
    - zstd
    - libgomp        # [linux]
    - llvm-openmp    # [osx]

test:
  commands:
    - dart --version
    - dart --help
    - dart predict --help
    - dart hits2emi --help
    - dart damage-annotate --help

about:
  home: https://github.com/genomewalker/dart
  license: MIT
  license_file: LICENSE
  summary: DART - Damage-Aware Read Translation for ancient DNA metagenomics
  doc_url: https://github.com/genomewalker/dart/wiki
  dev_url: https://github.com/genomewalker/dart

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
  recipe-maintainers:
    - genomewalker
