{% set name = "ngmaster" %}
{% set version = "2.0.7" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://github.com/MDU-PHL/ngmaster/archive/refs/tags/v{{ version }}.tar.gz"
  sha256: 174dc740da6427cc0e6510336ae53b4b3aff5ef0623de4d3d0c8577e14ff96f6

build:
  number: 0
  noarch: python
  entry_points:
    - ngmaster=ngmaster.run_ngmaster:main
  script: "{{ PYTHON }} -m pip install . -vvv --no-deps --no-build-isolation --no-cache-dir"
  run_exports:
    - {{ pin_subpackage('ngmaster', max_pin="x") }}

requirements:
  host:
    - python >=3.12
    - pip
    - setuptools
  run:
    - python >=3.12
    - biopython
    - mlst
    - requests
    - bs4
    - mlstdb ==1.0.0

test:
  imports:
    - ngmaster
  commands:
    - ngmaster --help
    - ngmaster --test

about:
  home: "https://github.com/MDU-PHL/ngmaster"
  license: "GPL-3.0-only"
  license_family: "GPL3"
  license_file: "LICENSE"
  summary: "In silico multi-antigen sequence typing for N. gonorrhoeae (NG-MAST and NG-STAR)."
  doc_url: "https://github.com/MDU-PHL/ngmaster/blob/master/README.md"
  dev_url: "https://github.com/MDU-PHL/ngmaster"

extra:
  recipe-maintainers:
    - stroehleina
    - kristyhoran
