{% set name = "seqfold" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 93c09d4557818ec221f5663b853bab7b3b7faa1471a004fbe9a67df255dcda3f
  patches:
    - requirements.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  run_exports:
    - {{ pin_subpackage(name|lower, max_pin="x.x") }}

requirements:
  host:
    - python >=3.5
    - pip
    - setuptools >=61.0
  run:
    - python >=3.5

test:
  imports:
    - seqfold
  commands:
    - pip check
    - seqfold --help
  requires:
    - pip

about:
  home: https://github.com/Lattice-Automation/seqfold
  summary: Predict the minimum free energy and structure of nucleic acids.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jonas-fuchs
